import type { Metadata } from "next";
import { Urbanist, Lilex } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import IntroLoader from "./IntroLoader";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

const lilex = Lilex({
  variable: "--font-lilex",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/logo_code.jpg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} ${lilex.variable} antialiased`}
      > 
        <IntroLoader />
        <Header />
        {children}
      </body>
    </html>
  );
}
